//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type SkillsChanges struct {
	ID           *int32 `sql:"primary_key"`
	DateChange   *time.Time
	WhoChangedID *string
	UserID       *string
	Skill        *string
	Rating       *int32
}
