//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Skills = newSkillsTable("", "skills", "")

type skillsTable struct {
	sqlite.Table

	// Columns
	ID     sqlite.ColumnInteger
	UserID sqlite.ColumnString
	Skill  sqlite.ColumnString
	Rating sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
}

type SkillsTable struct {
	skillsTable

	EXCLUDED skillsTable
}

// AS creates new SkillsTable with assigned alias
func (a SkillsTable) AS(alias string) *SkillsTable {
	return newSkillsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SkillsTable with assigned schema name
func (a SkillsTable) FromSchema(schemaName string) *SkillsTable {
	return newSkillsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SkillsTable with assigned table prefix
func (a SkillsTable) WithPrefix(prefix string) *SkillsTable {
	return newSkillsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SkillsTable with assigned table suffix
func (a SkillsTable) WithSuffix(suffix string) *SkillsTable {
	return newSkillsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSkillsTable(schemaName, tableName, alias string) *SkillsTable {
	return &SkillsTable{
		skillsTable: newSkillsTableImpl(schemaName, tableName, alias),
		EXCLUDED:    newSkillsTableImpl("", "excluded", ""),
	}
}

func newSkillsTableImpl(schemaName, tableName, alias string) skillsTable {
	var (
		IDColumn       = sqlite.IntegerColumn("id")
		UserIDColumn   = sqlite.StringColumn("user_id")
		SkillColumn    = sqlite.StringColumn("skill")
		RatingColumn   = sqlite.IntegerColumn("rating")
		allColumns     = sqlite.ColumnList{IDColumn, UserIDColumn, SkillColumn, RatingColumn}
		mutableColumns = sqlite.ColumnList{UserIDColumn, SkillColumn, RatingColumn}
	)

	return skillsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:     IDColumn,
		UserID: UserIDColumn,
		Skill:  SkillColumn,
		Rating: RatingColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
