//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type SkillHistories struct {
	ID           int32 `sql:"primary_key"`
	DateChange   *time.Time
	WhoChangedID *int32
	UserID       *int32
	Skill        *string
	Rating       *int32
}
