//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Skills struct {
	UserID *int32
	Skill  *string
	Rating *int32
}
