//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Users struct {
	ID           int32 `sql:"primary_key"`
	Name         *string
	Company      *string
	Email        *string
	Phone        *string
	Role         *string
	Salt         *string
	HashedSecret *string
}
