//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type UserHistories struct {
	ID           int32 `sql:"primary_key"`
	DateChange   *time.Time
	WhoChangedID *int32
	Name         *string
	Company      *string
	Email        *string
	Phone        *string
	Role         *string
	HashedSecret *string
}
